### ISSUE TITLE
Feature Request: Load multiple Event logs for two scenarios

### ISSUE THREAD

**Issue by chcart** [microsoft/EventLogExpert#106]
2 scenarios:
-Loading multiple logs from same source (May not need a Source computer column)
-Loading multiple logs from different sources.  (Would def need a Source computer column)

**Comment by bill-long** [comment]
Fixed by #121. File menu now lets you add more logs to the same view. Use the View menu to toggle Log Name and Computer Name columns to help make sense of it. Releasing this in a new build shortly.
