### ISSUE TITLE
Feature Request: Easy XML Filtering

### ISSUE THREAD

**Issue by chcart** [microsoft/EventLogExpert#107]
No one knows XPath.  So, offer a text box where engineer can paste in what they care about, without having to learn XPath.  
Scenario:
I need to know from this Security Log where TicketEncryptionType is equal to 0x17.  I have the below XML:
 <EventData>
  <Data Name="TargetUserName">admin@contoso.COM</Data> 
  <Data Name="TargetDomainName">contoso.COM</Data> 
  <Data Name="ServiceName">etype</Data> 
  <Data Name="ServiceSid">S-1-5-21-Stuff</Data> 
  <Data Name="TicketOptions">0x40810000</Data> 
  <Data Name="TicketEncryptionType">0x17</Data> 
  <Data Name="IpAddress">::ffff:A.B.C.D</Data> 
  <Data Name="IpPort">62460</Data> 
  <Data Name="Status">0x0</Data> 
  <Data Name="LogonGuid">{A644847E-D66F-589F-E458-528DC8D5443B}</Data> 
  <Data Name="TransmittedServices">-</Data> 
  </EventData>

In the filter text box, I just put this in:
<EventData>
<Data Name="TicketEncryptionType">0x17</Data> 
</EventData>

And then eventlog expert figures out the XML filter for me, and even offers the XPath query text.  Also, include ability to and/or things, and add * for wildcards (if XPath supports that)

**Comment by bill-long** [comment]
What event source and event ID is this example?

**Comment by chcart** [comment]
It looks like git stripped out what I wrote.  Here's a screenshot of what was supposed to be there:
![image](https://github.com/microsoft/EventLogExpert/assets/120026950/d136cd57-c7d5-42dc-88f3-18a88a3e6e05)
I don't know if that uploaded an image or not.  

Microsoft-Windows-Security-Auditing EventID 4769

**Comment by bill-long** [comment]
With the release that went live a couple of hours ago, you can click Add Advanced Filter. In the textbox type:

Xml.Contains("\"TicketEncryptionType\">0x17<")

I _think_ that will find these events.

**Comment by chcart** [comment]
Awesome!  I will test.

**Comment by bill-long** [comment]
Hmm, I do see these on a DC in my lab:

![image](https://github.com/microsoft/EventLogExpert/assets/4518572/03a5b5e6-7515-4f46-a077-b7bb8c61b735)

And I am able to filter by the TicketEncryptionType. All mine are -1, so if I filter for that:

![image](https://github.com/microsoft/EventLogExpert/assets/4518572/63514af6-6271-44e9-ade1-06d6baef6116)

But if I change it to something else, like -2:

![image](https://github.com/microsoft/EventLogExpert/assets/4518572/e8de223a-a7fd-4f6e-a220-5ebd6194cfd5)

So it seems to be working.
