### ISSUE TITLE
EVTX does not load in Eventlog Expert, loads 

### ISSUE THREAD

**Issue by HerbertMauerer** [microsoft/EventLogExpert#118]
I have an application eventlog I hapened to use for Eventlog Expert testing, and it does not load.

It loads fine and I can filter it in EvPro and in-box event viewer.

the first time I tried there was a note in the status line that it failed to load. In subsequent attempt it does nothing.

ODB link: https://microsofteur-my.sharepoint.com/:f:/g/personal/herbertm_microsoft_com/EuwlJpCKCTZFqEZ-t7Qv2OcB-qf77dmtuOBA08LdhFg74Q?e=mcMijR

**Comment by bill-long** [comment]
I tested this on my machine and it seems to load fine. Sent you a video.

**Comment by bill-long** [comment]
We stumbled across a bug that _might_ have been causing intermittent exceptions right when a log finishes loading. The fix is in the latest release.

**Comment by bill-long** [comment]
Hopefully this was fixed in one of the recent releases. Please reopen if not.
