### ISSUE TITLE
Security logs has option for keyword filtering

### ISSUE THREAD

**Issue by johnbay55** [microsoft/EventLogExpert#165]
When you open a security event log in event viewer
There is an option to filter on keywords and only show audit failed events.

This is very useful for logon failures because we only care about the failure events.  The same event id can be used for success or failure

I can't figure out how to filter on audit failures

**Comment by jschick04** [comment]
Right now you can use the advanced filter to search the XML but I will add Keyword filtering for "Audit Success/Failure"

**Comment by johnbay55** [comment]
I tried that option but I can't figure out to get the syntax right.

**Comment by bill-long** [comment]
#167 brings keyword strings to the DisplayEventModel. Then we just need to add the filter option in the UI.
