### ISSUE TITLE
Netlogon Source events not showing description

### ISSUE THREAD

**Issue by chcart** [microsoft/EventLogExpert#166]
I'm not sure when this stopped working.  Oldest Netlogon event says:
Description not found. No provider available.

**Comment by bill-long** [comment]
This is working for me:

![image](https://github.com/microsoft/EventLogExpert/assets/4518572/c592edef-c263-4ff3-b2b4-150a5c966383)

Is it a particular event ID? Are you using event databases or no?

**Comment by bill-long** [comment]
Ah, I think there might be a case sensitivity issue with the name of the provider. Sometimes it appears as NETLOGON, but the provider metadata has it mixed case, so if you're using databases, it might not find it. An immediate workaround is go to Tools->Options and disable all databases. This will make it switch to the local providers, which aren't case-sensitive.

PR coming up.
