### ISSUE TITLE
After Removal of filter, when event is selected, snap to that event in new view.

### ISSUE THREAD

**Issue by dpaulson45** [microsoft/EventLogExpert#198]
You create a filter to find a particular event. Then you select the event you want, remove the filter to see what other events are around it. However, you are snapped back to the top of the log. This is a different than the old version of Event Log Expert.

**Comment by bill-long** [comment]
Unfortunately this is impossible until this is resolved: https://github.com/dotnet/aspnetcore/issues/26943

Unless I implement my own virtualized view again, which I am trying not to do. So we'll probably wait for Virtualize to be enhanced to allow this.
