### ISSUE TITLE
Moving EventLogExpert window between monitors causes fault then crash

### ISSUE THREAD

**Issue by bluephyr** [microsoft/EventLogExpert#228]
When dragging the window for EventLogExpert between my main monitor and the monitors positioned above it, the window will erratically flash left-to-right and I can no longer move it. It eventually crashes.

**Comment by jschick04** [comment]
This seems like it could be a Windows snap issue. Do you have an application crash event in the event logs that you can paste the crashing stack from?

**Comment by bluephyr** [comment]
Hey Joseph,

I've gone ahead and recreated the issue, then went to Application events and found an Application Hang event. Not sure if that will be helpful. Here is both the WER event and the Application Hang details:

Information       7/10/2023 3:32:05 PM  Windows Error Reporting           1001     None

Fault bucket 1937576160567764292, type 5
Event Name: MoAppHang
Response: Not available
Cab Id: 0

Problem signature:
P1: eventlogexpert_23.7.6.1424_x64__8wekyb3d8bbwe
P2: praid:App
P3: 23.7.6.1424
P4: 648f9b5c
P5: 983b
P6: 134217728
P7:
P8:
P9:
P10:

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.68b1a7bf-e00f-4221-a791-62cee8938242.tmp.WERInternalMetadata.xml<file://%3f/C:/ProgramData/Microsoft/Windows/WER/Temp/WER.68b1a7bf-e00f-4221-a791-62cee8938242.tmp.WERInternalMetadata.xml>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.9b264c8f-cbdc-43de-8e3b-ed0ce48ef727.tmp.csv<file://%3f/C:/ProgramData/Microsoft/Windows/WER/Temp/WER.9b264c8f-cbdc-43de-8e3b-ed0ce48ef727.tmp.csv>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.a9017074-9393-464f-be7f-12f86882bce8.tmp.txt<file://%3f/C:/ProgramData/Microsoft/Windows/WER/Temp/WER.a9017074-9393-464f-be7f-12f86882bce8.tmp.txt>
\\?\C:\Users\nateguthrie\AppData\Local\Temp\WER.9b3c5a54-b620-4099-9bfd-2801f95e4b66.tmp.appcompat.txt<file://%3f/C:/Users/nateguthrie/AppData/Local/Temp/WER.9b3c5a54-b620-4099-9bfd-2801f95e4b66.tmp.appcompat.txt>
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.5f3db8f7-762b-4e3c-b64d-fb499fd50078.tmp.xml<file://%3f/C:/ProgramData/Microsoft/Windows/WER/Temp/WER.5f3db8f7-762b-4e3c-b64d-fb499fd50078.tmp.xml>

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppHang_eventlogexpert_2_c71721de7660eed472e962653a9fe55c4bf47e6_9c459126_149da836-744e-41b9-b1a0-825cb71c5c47<file://%3f/C:/ProgramData/Microsoft/Windows/WER/ReportArchive/AppHang_eventlogexpert_2_c71721de7660eed472e962653a9fe55c4bf47e6_9c459126_149da836-744e-41b9-b1a0-825cb71c5c47>

Analysis symbol:
Rechecking for solution: 0
Report Id: 02207555-42ad-4aa5-be7c-1c499efac106
Report Status: 268435456
Hashed bucket: 8081d3dd5faa76529ae3a74097e82544
Cab Guid: 0

...

Error      7/10/2023 3:32:06 PM  Application Hang           1002     Hanging Events

The program EventLogExpert.exe version 23.7.6.1424 stopped interacting with Windows and was closed. To see if more information about the problem is available, check the problem history in the Security and Maintenance control panel.



I may have misspoke, however. The application never fully crashes, it just never responds. That said, while the behavior was occurring, I was able to Create Dump File of the process for "EventLogExpert" using CPU at that time. It's around 600MB but let me know if you want me to compress it and send it anywhere.


Thank you!

Nate Guthrie
Support Engineer | Windows (On-Prem) Directory Services
Customer Service & Support | 9:00 AM - 6:00 PM CST Mon-Fri
Upcoming OOF: 7th, 12th, 19th
Manager: Steve Stoker | * ***@***.******@***.***>
***@***.***

**Comment by jschick04** [comment]
Pinged internally to get process dump.
For reference though, issue is with snapping constantly telling the app where to move to and MAUI is just trying to update the window position. I wouldn't expect any Rendering triggers to be called during this so only app activity currently executing is Program.Main (confirmed through the log file that Main is executed just once).

 ```
0 win32u!ZwUserSetWindowPos+0x14
 1 Microsoft_UI_Windowing_Core!Core::YieldAndCall::SetWindowPosNative::__l2::<lambda_a6233881b9748a0e26e17be933829335>::operator()+0x4b
 2 Microsoft_UI_Windowing_Core!CFlat::SehSafe::Execute<<lambda_a6233881b9748a0e26e17be933829335> >+0x5d
 3 Microsoft_UI_Windowing_Core!Core::YieldAndCall::SetWindowPosNative+0xa6
 4 Microsoft_UI_Windowing_Core!Core::YieldAndCall::SetWindowPos+0xb8
 5 Microsoft_UI_Windowing_Core!Windowing::AppWindow::SetPosition+0x79
 6 Microsoft_UI_Windowing_Core!Windowing::AppWindow::SetPosition+0x33
 7 Microsoft_UI_Windowing_Core!Windowing::AppWindow::Api_IAppWindow_Move$+0x40
 8 Microsoft_UI_Windowing_Core!Windowing::AppWindow::InterfaceImplementation$::_Api_IAppWindow::Dispatcher::Move+0x44
 9 Microsoft_UI_Windowing_Core!Api::IAppWindow::Interface$::StaticDispatcher::Move+0x2f
 a Microsoft_UI_Windowing_Core!Api::IAppWindow::Move+0x2f
 b Microsoft_UI_Windowing_Core!Api::IAppWindow::ExportAdapter$::Move+0xa7
 c Microsoft_Maui!Microsoft.Maui.Platform.WindowExtensions.UpdatePosition+0x164
```
