### ISSUE TITLE
Show text based hex values for system.bytes[]

### ISSUE THREAD

**Issue by maweeras-msft** [microsoft/EventLogExpert#230]
When looking at a live webauthn event log, event viewer will show it like so. Note the values in Request and clientdatahash.

Log Name:      Microsoft-Windows-WebAuthN/Operational
Source:        Microsoft-Windows-WebAuthN
Date:          22/08/2023 11:34:05
Event ID:      1103
Task Category: Cbor Encode GetAssertion Request
Level:         Information
Keywords:      Cbor,Ctap,WebAuthN
User:          contoso\johndoe
Computer:      pc2
Description:
Cbor encode GetAssertion request.

TransactionId: {fbc7ded0-09fa-474f-bdb2-bc796063c364}
RpId: github.com
ClientDataHashAlgId: SHA-256 ClientDataLength: 131 ClientDataHash: 0x94AB776CD9D4DE1941356D697B06A21C8E17786228C3B02B94FABD3B92693ACA
AllowCredentialCount: 2
Request: 0x02A4016A6769746875622E636F6D02582094AB776CD9D4DE1941356D697B06A21C8E17786228C3B02B94FABD3B92693ACA0382A362696458604A751DF0861076E839819227D1F94E66A24E8D9D287CE3E62E50F717D3A82286504C11A5C4291564B3BE023D4BA1969E62E9EA5284B61C21966CCA7BE3541350EA5D7A9647AD4989A1EB66E8FB875DEA952ADF77BAAAD5A9A5C67EEF2BFA0C5264747970656A7075626C69632D6B65796A7472616E73706F72747317A362696458209A46DFC3F7370D632D5648D5241F49676FAA6980EB6F3C7302532AFFA341572964747970656A7075626C69632D6B65796A7472616E73706F7274731705A1627570F5

Event Xml:

`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-WebAuthN" Guid="{3ae1ea61-c002-47fb-b06c-4022a8c98929}" />
    <EventID>1103</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>103</Task>
    <Opcode>12</Opcode>
    <Keywords>0x8000000000000007</Keywords>
    <TimeCreated SystemTime="2023-08-22T10:34:05.2743947Z" />
    <EventRecordID>88676</EventRecordID>
    <Correlation />
    <Execution ProcessID="9968" ThreadID="14352" />
    <Channel>Microsoft-Windows-WebAuthN/Operational</Channel>
    <Computer>pc2</Computer>
    <Security UserID="S-1-12-1-89862890-109492541-16185047-378728012" />
  </System>
  <EventData>
    <Data Name="TransactionId">{fbc7ded0-09fa-474f-bdb2-bc796063c364}</Data>
    <Data Name="RpId">github.com</Data>
    <Data Name="ClientDataHashAlgId">SHA-256</Data>
    <Data Name="ClientDataLength">131</Data>
    <Data Name="ClientDataHashLength">32</Data>
    <Data Name="ClientDataHash">94AB776CD9D4DE1941356D697B06A21C8E17786228C3B02B94FABD3B92693ACA</Data>
    <Data Name="CredentialCount">2</Data>
    <Data Name="RequestLength">253</Data>
    <Data Name="Request">02A4016A6769746875622E636F6D02582094AB776CD9D4DE1941356D697B06A21C8E17786228C3B02B94FABD3B92693ACA0382A362696458604A751DF0861076E839819227D1F94E66A24E8D9D287CE3E62E50F717D3A82286504C11A5C4291564B3BE023D4BA1969E62E9EA5284B61C21966CCA7BE3541350EA5D7A9647AD4989A1EB66E8FB875DEA952ADF77BAAAD5A9A5C67EEF2BFA0C5264747970656A7075626C69632D6B65796A7472616E73706F72747317A362696458209A46DFC3F7370D632D5648D5241F49676FAA6980EB6F3C7302532AFFA341572964747970656A7075626C69632D6B65796A7472616E73706F7274731705A1627570F5</Data>
  </EventData>
</Event>`

But event log expert shows it as 

Details
Source: Microsoft-Windows-WebAuthN
Event Id: 1103
Level: Information
Keywords: WebAuthN Ctap Cbor
Date and Time: 22/08/2023 11:34:05
Description:
Cbor encode GetAssertion request.

TransactionID: fbc7ded0-09fa-474f-bdb2-bc796063c364
RpID: github.com
ClientDataHashAlgID: SHA-256 ClientDataLength: 131 ClientDataHash: System.Byte[]
AllowCredentialCount: 2
Request: System.Byte[]

`<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-WebAuthN" />
    <EventID>1103</EventID>
    <Level>Information</Level>
    <Task>Cbor Encode GetAssertion Request</Task>
    <Keywords>0x8000000000000007</Keywords>
    <TimeCreated SystemTime="2023-08-22T10:34:05.2743947Z" />
    <EventRecordID>88676</EventRecordID>
    <Channel>Microsoft-Windows-WebAuthN/Operational</Channel>
    <Computer>pc2</Computer>
  </System>
  <EventData>
    <Data Name="TransactionId">fbc7ded0-09fa-474f-bdb2-bc796063c364</Data>
    <Data Name="RpId">github.com</Data>
    <Data Name="ClientDataHashAlgId">SHA-256</Data>
    <Data Name="ClientDataLength">131</Data>
    <Data Name="ClientDataHashLength">32</Data>
    <Data Name="ClientDataHash">System.Byte[]</Data>
    <Data Name="CredentialCount">2</Data>
    <Data Name="RequestLength">253</Data>
    <Data Name="Request">System.Byte[]</Data>
  </EventData>
</Event>
`

This makes it awkward when we want to extract a request to decode in a CBOR decoder like https://cbor.me.
We have to open the same event log in event viewer to get to the same event and extract the value from there.

Can we please show these values like in the event viewer in a future release?

**Comment by bill-long** [comment]
Do you know the steps to produce this event, or do you have an event log you can share which contains it?

**Comment by bill-long** [comment]
This is fixed in the prerelease that just went live.
