### ISSUE TITLE
have search term for ActivityId

### ISSUE THREAD

**Issue by HerbertMauerer** [microsoft/EventLogExpert#232]
as an extension to #163 where we ask for the ability to filter for content of the event XML, you could also have a specific ActivityId filter like you filter for description. This would make it easier to do GP operational and WDAC event analysis.

yeah, total luxury.

**Comment by maweeras-msft** [comment]
CorrelationID field is similar to this ask and one we use heavily for reviewing logs for AD FS. We then need to correlate a transaction of interest via this field to narrow down the log entries of interest as per https://learn.microsoft.com/en-us/windows-server/identity/ad-fs/troubleshooting/ad-fs-tshoot-logging#correlating-events . We currently dont see this at all in eventlog expert and would love to be able to do this filtering in a future release.
