### ISSUE TITLE
Ability to navigate events using up and down arrows on the keyboard 

### ISSUE THREAD

**Issue by ItsRalu** [microsoft/EventLogExpert#240]
Currently, the up and down arrow just scrolls up and down the application (as if using the scroll wheel on a mouse) without going to the next event if pressing the down arrow, or prior event if pressing the up arrow.

**Comment by jschick04** [comment]
Looks like this broke in a previous update.

**Comment by bill-long** [comment]
I would prefer arrow keys for this, but I thought we were stuck with tabs because arrow keys are bound to Virtualize and there's no easy way to change it. At least, that was the outcome of our discussion back in May.

**Comment by jschick04** [comment]
I believe that was the case but now that we have the ctrl+c handler, we should hopefully be able to override it there in that OnKeyUp handler.
