### ISSUE TITLE
Select position is lost when showing/hiding all events

### ISSUE THREAD

**Issue by bill-long** [microsoft/EventLogExpert#286]
* Create a filter where you're showing only those events.
* Select an event of interest.
* From the View menu check Show All Events.

At this point there's no easy way to get back to your selected event. If you click on a column header and then hit Tab, you're in a totally different location than the event you had selected. This makes it difficult to find the context around the event of interest you identified in the filtered view.

**Comment by jschick04** [comment]
Tab only works if the SelectedEvent is still within the rendered table rows. This is why Virtualize needs a way to scroll to index or we still need to come up with our own Virtualize replacement.
