### ISSUE TITLE
Scroll Bar difficult to use

### ISSUE THREAD

**Issue by nodrog285** [microsoft/EventLogExpert#317]
The Scroll bar and the scrolling "button" especially is very difficult to use because it is so small. As in "narrow" and almost hidden against the right edge of the window. Please make the scroll bar wider so I can grab the button. I'm opening logs that have 50-100k events and scrolling with the mouse wheel is too slow.

**Comment by jschick04** [comment]
Page up and page down can also be used within the table to scroll faster in the meantime while we look into this.

**Comment by jschick04** [comment]
This change is available in the latest prerelease, please let us know your feedback on if this change is acceptable or too wide now

**Comment by jschick04** [comment]
Latest prerelease is 24.2.23.1122 which contains the change. Relaunch or check for updates and it should pull it.

**Comment by nodrog285** [comment]
That just happened and yes it is wider now. Thank you.
