### ISSUE TITLE
clearing entries for imported event databases

### ISSUE THREAD

**Issue by maweeras-msft** [microsoft/EventLogExpert#319]
The current UX allows importing a database and to selectively enable/disable. But no means to clear an entry (say after its disabled) or to determine the file path it was loaded from. Can this be improved in the next release please

**Comment by jschick04** [comment]
Databases are located in the local app data "%localappdata%\Packages\eventlogexpert_8wekyb3d8bbwe\LocalState\Databases" where they can be removed and on app load they will no longer be imported.

We can look at adding an option to delete a database from the UI once it has been disabled.
