### ISSUE TITLE
Filter with XML string caused EventLogExpert to crash

### ISSUE THREAD

**Issue by scooteroc** [microsoft/EventLogExpert#349]
Looking at 3MB CAPI event log, Create this filter 
EventID eq 11, subfilter Level eq error, XML contains   subjectName="W60008306"
![Screenshot 2023-06-08 1726391](https://github.com/microsoft/EventLogExpert/assets/10049173/4573f0a5-9ccf-494b-b2bf-b40620ea3795)
The string, subjectName="W60008306" is text taken from the Event log XML.
EventLogExpert is crashes every time this filter is saved

Event ID 1000 - Application Error event: 
- EventData 
  AppName EventLogExpert.exe 
  AppVersion 24.5.15.1008 
  AppTimeStamp 661f0000 
  ModuleName Microsoft.ui.xaml.dll 
  ModuleVersion 3.1.5.0 
  ModuleTimeStamp 5c2afe3b 
  ExceptionCode c000027b 
  FaultingOffset 0000000000405175 
  ProcessId 0x166c 
  ProcessCreationTime 0x1daa8913669c783 
  AppPath C:\Program Files\WindowsApps\eventlogexpert_24.5.15.1008_x64__8wekyb3d8bbwe\EventLogExpert.exe 
  ModulePath C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.5_5001.119.156.0_x64__8wekyb3d8bbwe\Microsoft.ui.xaml.dll 
  IntegratorReportId 2be5eac8-97e9-4259-9217-aae920af3a7a 
  PackageFullName eventlogexpert_24.5.15.1008_x64__8wekyb3d8bbwe 
  PackageRelativeAppId App

**Comment by jschick04** [comment]
This is more than likely due to the quotes not being escaped

**Comment by scooteroc** [comment]
Removed quotes, all records are filtered now. I will look at escape chars

**Comment by jschick04** [comment]
Just use a \\" instead of " but there is an issue with the LINQ even with the escaped characters that I am working out and then I should have a PR available for this fix

**Comment by jschick04** [comment]
So issue isn't actually with the escape characters, even though the XML output shows \" it is actually a \' when the string is checked so changing the filter query to use \' should resolve this issue
