### ISSUE TITLE
Tool crashed while load all event log files

### ISSUE THREAD

**Issue by diskman79** [microsoft/EventLogExpert#378]
[Microsoft-Windows-event-log.zip](https://github.com/user-attachments/files/17615994/Microsoft-Windows-event-log.zip)
Tool crashed while load all event log files, please try with this sample logs.

**Comment by diskman79** [comment]
This Event log is captured from Win11 24H2, and tool crahes while running in 23H2.
I re-tried with system Win11 24H2, and it is no problem there.

**Comment by jschick04** [comment]
Which file in that zip is crashing?
