### ISSUE TITLE
Date filter does not work as expected

### ISSUE THREAD

**Issue by xoere2** [microsoft/EventLogExpert#383]
I am trying to filter a Windows Event Log using the Date filter. Sometimes it shows no results even though there are items in the date range. Sometimes it shows results outside of the specified date range. To reproduce, try date filtering an Event Log file on v24.8.29.1017.

**Comment by jschick04** [comment]
I can't reproduce, do you have a screen shot of an example where it is not working?

**Comment by jschick04** [comment]
I see that you have set the time zone settings to UTC based on the Date and Time column.

My assumption would be that the filter is working correctly but the filtering time is off due to that offset.

If you go into settings and set the time zone to your systems time zone, does the issues go away?
