### ISSUE TITLE
Date filter does not work as expected - Reopen of #383

### ISSUE THREAD

**Issue by xoere2** [microsoft/EventLogExpert#393]
I am trying to filter a Windows Event Log using the Date filter. Sometimes it shows no results even though there are items in the date range. Sometimes it shows results outside of the specified date range. To reproduce, try date filtering an Event Log file on v24.8.29.1017.

Exhibit 1: Showing events before the specified time range
![Image](https://github.com/user-attachments/assets/5ac12a1f-d152-40c4-9fb2-0fd914ff7e31)

Exhibit 2: Showing events after the specified time range
![Image](https://github.com/user-attachments/assets/60d9bee2-a7a6-4564-bf04-aa7c9e7b074d)

Exhibit 3: Showing **the same filter as in Exhibit 1 and 2**, but after having disabled and re-enabled it. **It now shows no events.**
![Image](https://github.com/user-attachments/assets/8eeb58b7-9bcc-4f5b-a85e-1773bf2ebb1d)

In the previous post, it was suggested that the UTC time zone for Event Log Expert may be causing an offset from my configured system time.
I tried setting Event Log Expert to my configured system time, but it still shows events outside of the time range.
Please do not close, this filter feature is broken.

Exhibit 4: Event Log Expert configured to show in my configured system time, but still showing events outside of time range.
![Image](https://github.com/user-attachments/assets/ea0ca656-6d8c-490f-b511-2b6aa15ee618)

**Comment by jschick04** [comment]
This should be fixed on the preview build.

Enable "Pre-release Builds" in the settings menu and check for updates to get the latest preview build.

**Comment by xoere2** [comment]
Thank you.
