### ISSUE TITLE
Add ability for color rules/color coding

### ISSUE THREAD

**Issue by gpauli86** [microsoft/EventLogExpert#60]
Add the ability highlight certain items colors.
For example: color code RED for system shutdown/restart events and then color code BLUE for PNP events leading up to it, etc.

Similar as notepad++ or TAT tool for highlighting strings or items.

**Comment by gpauli86** [comment]
+color "rules" should be able to be exportable separate from filter.

**Comment by HerbertMauerer** [comment]
I want this, too.

**Comment by rizwan3d** [comment]
Shutdown Event IDs
Event ID | Description
-- | --
41 | The system has rebooted without cleanly shutting down first.
1074 | The system has been shutdown properly by a user or process.
1076 | Follows after Event ID 6008 and means that the first user with shutdown privileges logged on to the server after an unexpected restart or shutdown and specified the cause.
6005 | The Event Log service was started. Indicates the system startup.
6006 | The Event Log service was stopped. Indicates the proper system shutdown.
6008 | The previous system shutdown was unexpected.
6009 | The operating system version detected at the system startup.
6013 | The system uptime in seconds.

PNP Event IDs
Event ID | Description
-- | --
6416 | A new external device was recognized by the System
6419 | A request was made to disable a device
6420 | A device was disabled.
6421 | A request was made to enable a device.
6422 | A device was enabled.
6423 | The installation of this device is forbidden by system policy.
6424 | The installation of this device was allowed, after having previously been forbidden by policy.

**Comment by jschick04** [comment]
This is added in #279 and available in the latest prerelease.

Took the TAT approach and added a view menu option to show all events when filter rules are in place.

Will create another issue for feature request to export color rules.
