### ISSUE TITLE
Ability to review multiple offline evtx files at once, side by side, etc

### ISSUE THREAD

**Issue by gpauli86** [microsoft/EventLogExpert#61]
Ability to have multiple evtx open from different systems (or same) to look for differences. Reviewing good vs bad, etc.

**Comment by HerbertMauerer** [comment]
I want this, too.

**Comment by bill-long** [comment]
@gpauli86 @HerbertMauerer  You can double-click on two evtx files and put the windows next to each other. Is this request for something more than that? Can we get some clarification?

**Comment by gpauli86** [comment]
@bill-long I believe the idea was to have 2 open in the same "session" so you can compare them. Potentially, even scrolling in one by time and the other scrolls too.

**Comment by bill-long** [comment]
You can open two in the same view now, but they are mixed together in the same table. This is useful for things lining up events between the Application Log and System Log, or between two Application logs from two different servers, etc. It turns them into one big log, effectively. The View menu lets you add a couple of columns to help tell them apart.

A side-by-side view where it tries to line up two logs and scroll them at the same time would be interesting to implement.

**Comment by jschick04** [comment]
With the recent changes to the event table, I think we could easily implement a side by side table for each open log. Having them scroll at the same time may be a bit more of a challenge.

Would just need to put the list of tables in a flex group and remove the hidden parameter but I would imagine that a side by side view would be very cramped.

With the combined view and the recent addition of highlighting, is this a feature that still has interest?

**Comment by jschick04** [comment]
Closing this for now, we can reopen later if there is further interest in further side by side discussion.
