### ISSUE TITLE
Ability to review multiple offline evtx files at once in a timeline view 

### ISSUE THREAD

**Issue by gpauli86** [microsoft/EventLogExpert#62]
Ability to open multiple evtx in one single pane to understand timeline.
Ex: fail over cluster where you need to review multiple evtx from systems to see when fail over happened then understand what happened on the cluster, etc.

(one pane, making sure the machine name is one of the columns to note which evtx/machine the event came from)

**Comment by HerbertMauerer** [comment]
I want this, too.
