### ISSUE TITLE
Can't use mouse wheel to scroll source list (may also apply to other filter items)

### ISSUE THREAD

**Issue by HerbertMauerer** [microsoft/EventLogExpert#84]
When you add a filter per source and you drop down the list:
https://microsofteur-my.sharepoint.com/:i:/g/personal/herbertm_microsoft_com/Eff0zFh-Km1JtyePE3MHJSsBBwXJSEqNRBle6B1iBTrQZw?e=WPQjdq

You can’t just scroll with the mouse wheel. This closes the drop-down.

**Comment by jschick04** [comment]
Scrolling with mouse should work fine, I am not able to repro that issue on any of my devices.

**Comment by HerbertMauerer** [comment]
do you have multiple screens?

what is the OS?

note same happens here when you are in settings dialog in the list of time-zones.

**Comment by jschick04** [comment]
Windows 10 and 11 and tried on my main system that has 3 and both my laptops

**Comment by jschick04** [comment]
Closing this for now, can reopen if we get more reports or are able to get a repro
