### ISSUE TITLE
Set hotkey for copying event to clipboard

### ISSUE THREAD

**Issue by HerbertMauerer** [microsoft/EventLogExpert#85]
Ctrl-C on an Event does nothing. It should copy the event text to the clipboard.
EvPro has summary and full copy, and also cumulative event copy. These are not this high priority...

**Comment by HerbertMauerer** [comment]
OK, I find it as "Copy Details" when an event is selected.

**Comment by jschick04** [comment]
"Copy Details" bug was fixed a while back so updating the title on this issue to reflect the first comment.

> Ctrl-C on an Event does nothing. It should copy the event text to the clipboard. EvPro has summary and full copy, and also cumulative event copy. These are not this high priority...
