### ISSUE TITLE
Ability to allow 'Copy' option to have a '1 line output' option

### ISSUE THREAD

**Issue by ivaldesMSFT** [microsoft/EventLogExpert#89]
(from previous version feedback shared with Bill, to have this tracked on this new version as well)

When working with multiple evtx files, filtering and sharing analysis with customers, it is useful to be able to copy & paste 1/multiple events in a ‘1 line’ type of output format , like this
 
 
Information       06/10/2022 11:31:11     Microsoft-Windows-Shell-Core              28019   (28179) AppResolver Cache Committed.
Information       06/10/2022 11:31:11     Microsoft-Windows-Shell-Core              28018   (28177) AppResolver Scan Stopped.
 
EventLogExpert would allow to multiple select and copy and the output is extended table type of  
 
LogName:       Microsoft-Windows-Shell-Core/Operational
Source:        Microsoft-Windows-Shell-Core
Date:          10/6/2022, 11:31:11 AM
Event ID:      28019
Task Category: Shell32_AppResolver_CacheCommitted
Level:         Information
User:          yzx
Computer:      xyz
Description:
AppResolver Cache Committed.
 
LogName:       Microsoft-Windows-Shell-Core/Operational
Source:        Microsoft-Windows-Shell-Core
Date:          10/6/2022, 11:31:11 AM
Event ID:      28018
Task Category: Shell32_AppResolver_Scan
Level:         Information
User:          yz
Computer:      xyz
Description:
AppResolver Scan Stopped.

**Comment by jschick04** [comment]
Resolved #227
