### ISSUE TITLE
Suggestions for Settings

### ISSUE THREAD

**Issue by HerbertMauerer** [microsoft/EventLogExpert#90]
I suggest having:

1. define what fields to copy when you copy an event. I would for example default to excluding "Log Name"
2. Setting to open new files (File/Open, double-click, drag&drop) in new window.
3. Color filtering configuration, including saving and loading it.
4. pre-defined Filter list, including saving and loading it.

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/EventLogExpert/issues/282
- [ ] https://github.com/microsoft/EventLogExpert/issues/283
```

**Comment by bill-long** [comment]
Note that double-click does currently open files in a new window, and any other behavior with double-click would be very odd. I don't think that should be selectable, or if it is, it should _default_ to a new window unless you change it to do something else.
